version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URI: ${API_URI}
        NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
