name: Docker Compose Build and Test Check

on:
  pull_request:
    branches:
      - staging
      - main
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: [self-hosted, power]
    environment: ${{ github.ref_name == 'staging' && 'staging' || 'production' }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Ensure Docker Compose is installed
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get update
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install -y docker-compose

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Stop and Remove Containers
        if: always()
        run: docker-compose down
