name: Docker Compose Build and Test Check

on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: [self-hosted, power]
    environment: staging
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Debug Environment
        run: printenv | grep -E 'NEXT_PUBLIC_API_URL|PORT|NODE_ENV'

      - name: CURL API
        run: curl -v ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Build Docker Compose
        run: |
          docker compose build --build-arg API_URI=${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Stop and Remove Containers
        if: always()
        run: docker compose down
