name: Docker Compose Build and Test Check

on:
  pull_request:
    branches:
      - staging
      - main
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Make sure docker compose is installed
        run: docker-compose --version || sudo apt-get install -y docker-compose

      - name: Determine .env file to use
        id: env-file
        run: echo "ENV_FILE=fe-env" >> $GITHUB_ENV

      - name: Validate env file
        run: echo "Using env file:" && echo ${{ env.ENV_FILE }}

      - name: Build Docker Compose
        run: docker-compose --env-file ${{ env.ENV_FILE }} build

      - name: Run Docker Compose
        run: docker-compose --env-file ${{ env.ENV_FILE }} up -d

      - name: Stop and Remove Containers
        if: always()
        run: docker-compose down
