name: ESLint Check

on:
  pull_request:
    branches:
      - development
      - staging
      - main

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
